apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: test-user
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      # Example ACL rules for consuming from my-topic using consumer group my-group
      - resource:
          type: topic
          name: test-topic
          patternType: literal
        operation: Read
        host: "*"
      - resource:
          type: topic
          name: test-topic
          patternType: literal
        operation: Describe
        host: "*"
      - resource:
          type: group
          name: test-group
          patternType: literal
        operation: Read
        host: "*"
      # Example ACL rules for producing to topic my-topic
      - resource:
          type: topic
          name: test-topic
          patternType: literal
        operation: Write
        host: "*"
      - resource:
          type: topic
          name: test-topic
          patternType: literal
        operation: Create
        host: "*"
      - resource:
          type: topic
          name: test-topic
          patternType: literal
        operation: Describe
        host: "*"